# Generated by Django 3.0.8 on 2020-07-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_profit', models.FloatField()),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='wallets.Wallet')),
                ('to_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='wallets.Wallet')),
            ],
        ),
    ]
