# Generated by Django 3.0.8 on 2020-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='platform_profit',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=100),
        ),
    ]
