# Generated by Django 3.0.8 on 2020-07-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bts',
            field=models.FloatField(default=1),
        ),
    ]
