# Generated by Django 3.0.8 on 2020-07-28 11:57

from django.db import migrations, models
import wallets.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='id',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(default=wallets.models.generate_wallet_address, max_length=100, primary_key=True, serialize=False),
        ),
    ]
