# Generated by Django 3.0.8 on 2020-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20200728_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
